src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $datetime_order = null;

    #[ORM\Column(length: 255)]
    private ?string $status_order = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cart $cart = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateTimeOrder(): ?\DateTimeInterface
    {
        return $this->datetime_order;
    }

    public function setDateTimeOrder(\DateTimeInterface $datetime_order): static
    {
        $this->datetime_order = $datetime_order;

        return $this;
    }

    public function getStatusOrder(): ?string
    {
        return $this->status_order;
    }

    public function setStatusOrder(string $status_order): static
    {
        $this->status_order = $status_order;

        return $this;
    }

    public function getCart(): ?Cart
    {
        return $this->cart;
    }

    public function setCart(?Cart $cart): static
    {
        $this->cart = $cart;

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Order;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('datetime_order')
            ->add('status_order')
            ->add('cart')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Form\OrderType;
use App\Repository\OrderRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/order')]
class OrderController extends AbstractController
{
    #[Route('/', name: 'app_order_index', methods: ['GET'])]
    public function index(OrderRepository $orderRepository): Response
    {
        return $this->render('order/index.html.twig', [
            'orders' => $orderRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_order_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $order = new Order();
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($order);
            $entityManager->flush();

            return $this->redirectToRoute('app_order_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('order/new.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_order_show', methods: ['GET'])]
    public function show(Order $order): Response
    {
        return $this->render('order/show.html.twig', [
            'order' => $order,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_order_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Order $order, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_order_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('order/edit.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_order_delete', methods: ['POST'])]
    public function delete(Request $request, Order $order, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$order->getId(), $request->request->get('_token'))) {
            $entityManager->remove($order);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_order_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/order/_delete_form.html.twig
<form method="post" action="{{ path('app_order_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="btn">Delete</button>
</form>

templates/order/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/order/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Order{% endblock %}

{% block body %}
    <h1>Edit Order</h1>

    {{ include('order/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_order_index') }}">back to list</a>

    {{ include('order/_delete_form.html.twig') }}
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order index{% endblock %}

{% block body %}
    <h1>Order index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Datetime_order</th>
                <th>Status_order</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.datetimeOrder ? order.datetimeOrder|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ order.statusOrder }}</td>
                <td>
                    <a href="{{ path('app_order_show', {'id': order.id}) }}">show</a>
                    <a href="{{ path('app_order_edit', {'id': order.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_order_new') }}">Create new</a>
{% endblock %}

templates/order/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Order{% endblock %}

{% block body %}
    <h1>Create new Order</h1>

    {{ include('order/_form.html.twig') }}

    <a href="{{ path('app_order_index') }}">back to list</a>
{% endblock %}

templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}
    <h1>Order</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ order.id }}</td>
            </tr>
            <tr>
                <th>Datetime_order</th>
                <td>{{ order.datetimeOrder ? order.datetimeOrder|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Status_order</th>
                <td>{{ order.statusOrder }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_order_index') }}">back to list</a>

    <a href="{{ path('app_order_edit', {'id': order.id}) }}">edit</a>

    {{ include('order/_delete_form.html.twig') }}
{% endblock %}